import colors from "vuetify/lib/util/colors";
export default {
    theme: {
        options: {
            customProperties: true,
        },
        themes: {
            light: {
                ...colors,
                primary: "#1976D2",
                secondary: "#424242",
                accent: "#82B1FF",
                error: "#FF5252",
                info: "#2196F3",
                success: "#4CAF50",
                warning: "#FFC107",
                light: "#ffffff",
                danger: "#E8245F",
                mainBgColor: "#E5E5E5",
                subBgColor: "#F9FAFB",
                altBgColor: "#434343",
                header: "#333333",
                subBlue: "#DFE8FC",
                electricBlue: "#2254D3",
                "title-text": "#000000",
                "subtitle-text": "#4D4D4D",
                gray: "#E2E2E2",
                lightGray: "#F5F5F5",
                "border-gray": "#EBEBEB",
            },
            dark: {
                ...colors,
                primary: "",
                secondary: "",
                accent: "",
                error: "",
                info: "",
                success: "",
                warning: "",
                light: "#ffffff",
                danger: "#E8245F",
                mainBgColor: "#E5E5E5",
                subBgColor: "#F9FAFB",
                altBgColor: "#434343",
                header: "#333333",
                subBlue: "#DFE8FC",
                electricBlue: "#2254D3",
                "title-text": "#000000",
                "subtitle-text": "#4D4D4D",
                gray: "#E2E2E2",
                lightGray: "#F5F5F5",
                "border-gray": "#EBEBEB",
            },
        },
    },
    icons: {
        iconfont: "mdi",
    },
};